// Global Success 11 — textbook Listening, one section per Unit.
// Audio/video is embedded from the external source; no synthetic TTS.
const listeningSources = {
  'Unit 1': {type:'youtube', id:'0HaEqjbj9zQ', start:36, label:'Unit 1 Listening · Food and health', page:'https://loigiaihay.com/tieng-anh-11-unit-1-listening-a135509.html'},
  'Unit 2': {type:'youtube', id:'CxYb5sqSIqA', start:0, label:'Unit 2 Listening · Family conflicts', page:'https://langgo.edu.vn/tieng-anh-11-unit-2-listening'},
  'Unit 3': {type:'youtube', id:'3xbe4d9R_SM', start:0, label:'Unit 3 Listening · Living in a smart city', page:'https://langgo.edu.vn/tieng-anh-11-unit-3-listening'},
  'Unit 4': {type:'youtube', id:'_EPNZi3ZZTY', start:492, label:'Unit 4 Listening · ASEAN School Tour Programme', page:'https://langgo.edu.vn/tieng-anh-11-unit-4-listening'},
  'Unit 5': {type:'youtube', id:'aMWGI-XxIeE', start:567, label:'Unit 5 Listening · Black carbon and global temperature', page:'https://langgo.edu.vn/tieng-anh-11-unit-5-listening'},
  'Unit 6': {type:'youtube', id:'pCTqL-6JXeA', start:58, label:'Unit 6 Listening · A trip to Trang An', page:'https://langgo.edu.vn/tieng-anh-11-unit-6-listening'},
  'Unit 7': {type:'youtube', id:'KsK0r4lsqyE', start:0, label:'Unit 7 Listening · Vocational courses', page:'https://langgo.edu.vn/tieng-anh-11-unit-7-listening'},
  'Unit 8': {type:'youtube', id:'B6LbQ9i2F1w', start:154, label:'Unit 8 Listening · Becoming independent learners', page:'https://langgo.edu.vn/tieng-anh-11-unit-8-listening'},
  'Unit 9': {type:'youtube', id:'01RLsTvZJPc', start:173, label:'Unit 9 Listening · Types of bullying', page:'https://langgo.edu.vn/tieng-anh-11-unit-9-listening'},
  'Unit 10': {type:'youtube', id:'drRhnPqZeeY', start:0, label:'Unit 10 Listening · Human impact on ecosystems', page:'https://zim.vn/tieng-anh-11-unit-10-listening'}
};

// Six-answer school-test overlay for the original textbook Listening audio.
// The blanks are keyed to information in the corresponding textbook listening.
const listeningBank = [
{unit:'Unit 1',title:'Food and health',sourcePage:'https://loigiaihay.com/tieng-anh-11-unit-1-listening-a135509.html',prompts:['Teens should avoid food that contains a lot of ________.','Green vegetables can help teens ________ better.','Eggs and fish can help teens become taller and ________.','A healthy diet cannot replace ________.','Sugary desserts and drinks should be ________ down.','Healthy food can improve brain health and ________.'],blanks:['sugar','concentrate','stronger','exercise','cut','memory']},
{unit:'Unit 2',title:'Family conflicts',sourcePage:'https://langgo.edu.vn/tieng-anh-11-unit-2-listening',prompts:["Mai's mother keeps complaining about her ________.","Mai is not allowed to wear tight jeans at ________.",'Kevin mainly uses his smartphone and laptop for his ________.','Mai thinks Kevin’s parents may worry about his ________.','Kevin’s parents take away his phone and laptop at ________.','Mai’s mother also dislikes her choice of clothes and ________.'],blanks:['appearance','school','homework','eyesight','10 p.m.','hairstyle']},
{unit:'Unit 3',title:'Living in a smart city',sourcePage:'https://langgo.edu.vn/tieng-anh-11-unit-3-listening',prompts:['Ms Stevens is worried about losing her right to ________.','Cameras and ________ collect information about people.','Smart technologies can help with daily household ________.','People may interact with very few people face to ________.','Many activities can be done ________.','There may be little sense of ________ in the neighbourhood.'],blanks:['privacy','sensors','chores','face','online','community']},
{unit:'Unit 4',title:'ASEAN School Tour Programme',sourcePage:'https://langgo.edu.vn/tieng-anh-11-unit-4-listening',prompts:['The foreign students will visit the school on the 5th of ________.','They will spend ________ day at the school.','Their tour in Viet Nam lasts ________ days.','After Viet Nam, the students will go to ________.','Phong is working with members of the school’s ________ Union.','The school is preparing a special ________ to welcome the visitors.'],blanks:['May','one','five','Indonesia','Youth','event']},
{unit:'Unit 5',title:'Black carbon and global temperature',sourcePage:'https://langgo.edu.vn/tieng-anh-11-unit-5-listening',prompts:['Black carbon is also known as ________.','It consists of tiny pieces of black ________.','It mainly comes from forest fires and burning ________ fuels.','Burning ________ waste is a major source of soot.','Black carbon plays a role in global ________.','Burning crop waste is bad for the ________.'],blanks:['soot','dust','fossil','crop','warming','soil']},
{unit:'Unit 6',title:'A trip to Trang An Scenic Landscape Complex',sourcePage:'https://langgo.edu.vn/tieng-anh-11-unit-6-listening',prompts:['Trang An was recognised by UNESCO as a mixed World Heritage Site in ________.','The site consists of ________ protected areas.','The areas are linked by limestone mountains, ________ and rivers.','Trang An is famous for its beautiful landscape and long ________ history.','Most of the site is still in its ________ state.','The tour guide is named ________.'],blanks:['2014','three','valleys','cultural','natural','Thanh']},
{unit:'Unit 7',title:'Vocational courses',sourcePage:'https://langgo.edu.vn/tieng-anh-11-unit-7-listening',prompts:['Short cooking courses usually last two to three ________.','Professional cooking courses take ________ years.','Professional courses train people to be restaurant ________.','Students can work as an ________ in a real restaurant.','The school offers a wide range of ________.','Detailed information is available in the school ________.'],blanks:['months','two','cooks','apprentice','courses','brochure']},
{unit:'Unit 8',title:'Becoming independent learners',sourcePage:'https://langgo.edu.vn/tieng-anh-11-unit-8-listening',prompts:['The website lists ________ main characteristics of independent learners.','Independent learners are responsible for their own ________.','They set learning goals and make detailed study ________.','They are not afraid of asking difficult ________.','They enjoy learning ________ things.','They do not wait for parents or teachers to tell them what to ________.'],blanks:['four','learning','plans','questions','new','do']},
{unit:'Unit 9',title:'Types of bullying',sourcePage:'https://langgo.edu.vn/tieng-anh-11-unit-9-listening',prompts:['Technology has made bullying more ________ on social media.','Mai’s friend was a victim of ________.','Some people posted rude comments about her ________.','Body shaming is a common form of ________.','The students plan to start a campaign against ________.','The campaign is about bullying among ________.'],blanks:['common','cyberbullying','weight','cyberbullying','bullying','teenagers']},
{unit:'Unit 10',title:'Human impact on ecosystems',sourcePage:'https://zim.vn/tieng-anh-11-unit-10-listening',prompts:['Dr Logan is an expert in biodiversity ________.','A healthy ecosystem helps clean our air and ________.','Half of the world’s coral ________ have disappeared.','Humans have cut down about one ________ of the world’s forests.','As species disappear, the food ________ may break down.','We may run out of food and face more natural ________.'],blanks:['conservation','water','reefs','third','chain','disasters']}
];
